/*
 * Copyright 2018 75py
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// generated by work/generate_extentions_res.py
// template: work/template.HookTest.java

package com.nagopy.android.downloadconfirm.extension;

import android.support.test.runner.AndroidJUnit4;

import com.nagopy.android.downloadconfirm.R;

import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(AndroidJUnit4.class)
public class {{ extInfo.ext.capitalize() }}HookTest extends HookTest {

{% if extInfo.ext.lower() == "pdf" %}
    @org.junit.Ignore
{% endif %}
    @Test
    public void test{{ extInfo.ext.capitalize() }}HookEnabled() throws Throwable {
        testCheckboxOn("{{ extInfo.ext.lower() }}", R.string.label_{{ extInfo.ext.lower() }});
    }

    @Test
    public void test{{ extInfo.ext.capitalize() }}HookDisabled() throws Throwable {
        testCheckboxOff("{{ extInfo.ext.lower() }}");
    }
}
