// generated by work/generate_extentions_res.py
// template: work/template.ConfirmActivity.java

package com.nagopy.android.downloadconfirm.extension;

import com.nagopy.android.downloadconfirm.AbstractConfirmActivity;

public class ApkConfirmActivity extends AbstractConfirmActivity {
}